# For running Kapp inside a Kubernetes/Minikube container
apiVersion: v1
kind: Service
metadata:
  name: kapp-service
spec:
  type: NodePort
  selector:
    app: kapp
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapp-deployment
  labels:
    app: kapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapp
  template:
    metadata:
      labels:
        app: kapp
    spec:
      containers:
      - name: kapp
        image: kapp:<version>
        imagePullPolicy: Never
        ports:
        - containerPort: 1080
        env:
        - name: KAPP_HTTPS
          value: 'false'
        - name: KAPP_NETWORK
          value: '0.0.0.0'
        - name: KAPP_NETWORK_FILTER_IP_DISABLED
          value: 'false'
        - name: KAPP_DB_ACTIVE
          value: 'sqlite'
        - name: KAPP_MYSQL_URL
          value: 'myurl1'
        - name: KAPP_MYSQL_PORT
          value: '3306'
        - name: KAPP_MYSQL_CNX_LIMIT
          value: '10'
        - name: KAPP_MYSQL_DATABASE
          value: 'mydb1'
        - name: KAPP_MYSQL_USER
          value: 'myuser1'
        - name: KAPP_MYSQL_PASSWORD
          value: 'mypwd1'
        - name: KAPP_MONGO_URL
          value: 'monurl1'
        - name: KAPP_MONGO_DATABASE
          value: 'mondb1'
        - name: KAPP_MONGO_USER
          value: 'monuser1'
        - name: KAPP_MONGO_PASSWORD
          value: 'monpdw1'
