sudo: false
language: node_js
node_js:
  - "14"
notifications:
  email: false
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - rm -rf ./node_modules package-lock.json
  - npm uninstall -save-dev husky
  - npm install
script:
  - npm run app &
  - npm run test
  - npm run check-coverage
after_success:
  - npm run report-coverage
