dist: trusty
sudo: required
language: node_js
node_js:
  - "14"
notifications:
  email: false
before_install:
  - npm i -g npm@^2.0.0
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
env:
  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_script:
  - npm prune
script:
  - npm run app &
  - npm run test
  - npm run check-coverage
after_success:
  - npm run report-coverage
